export const chennaiConfig = {
  city: "Chennai",
  citySlug: "chennai",
  region: "Tamil Nadu",
  heroImage: "/images/site/chennai-service-directory-montage.png",
  serviceImage: "/images/site/chennai-article-anchor-detail.png",
  areaImage: "/images/site/chennai-area-balcony-safety-view.png",
  areas: [
    { name: "Adambakkam", slug: "adambakkam" },
    { name: "Adyar", slug: "adyar" },
    { name: "Alandur", slug: "alandur" },
    { name: "Ambattur", slug: "ambattur" },
    { name: "Aminjikarai", slug: "aminjikarai" },
    { name: "Anna Nagar", slug: "anna-nagar" },
    { name: "Arumbakkam", slug: "arumbakkam" },
    { name: "Ashok Nagar", slug: "ashok-nagar" },
    { name: "Avadi", slug: "avadi" },
    { name: "Ayanavaram", slug: "ayanavaram" },
    { name: "Besant Nagar", slug: "besant-nagar" },
    { name: "Chetpet", slug: "chetpet" },
    { name: "Choolaimedu", slug: "choolaimedu" },
    { name: "Chromepet", slug: "chromepet" },
    { name: "Egmore", slug: "egmore" },
    { name: "Ekkattuthangal", slug: "ekkattuthangal" },
    { name: "Guindy", slug: "guindy" },
    { name: "Injambakkam", slug: "injambakkam" },
    { name: "Iyyappanthangal", slug: "iyyappanthangal" },
    { name: "K K Nagar", slug: "k-k-nagar" },
    { name: "Kandanchavadi", slug: "kandanchavadi" },
    { name: "Karapakkam", slug: "karapakkam" },
    { name: "Kelambakkam", slug: "kelambakkam" },
    { name: "Kilpauk", slug: "kilpauk" },
    { name: "Kodambakkam", slug: "kodambakkam" },
    { name: "Kolathur", slug: "kolathur" },
    { name: "Korattur", slug: "korattur" },
    { name: "Kottivakkam", slug: "kottivakkam" },
    { name: "Koyambedu", slug: "koyambedu" },
    { name: "Madipakkam", slug: "madipakkam" },
    { name: "Madhavaram", slug: "madhavaram" },
    { name: "Manapakkam", slug: "manapakkam" },
    { name: "Mandaveli", slug: "mandaveli" },
    { name: "Medavakkam", slug: "medavakkam" },
    { name: "Mogappair", slug: "mogappair" },
    { name: "Mugalivakkam", slug: "mugalivakkam" },
    { name: "Mylapore", slug: "mylapore" },
    { name: "Nanganallur", slug: "nanganallur" },
    { name: "Navalur", slug: "navalur" },
    { name: "Neelankarai", slug: "neelankarai" },
    { name: "Nungambakkam", slug: "nungambakkam" },
    { name: "Palavakkam", slug: "palavakkam" },
    { name: "Pallavaram", slug: "pallavaram" },
    { name: "Pallikaranai", slug: "pallikaranai" },
    { name: "Perambur", slug: "perambur" },
    { name: "Periyar Nagar", slug: "periyar-nagar" },
    { name: "Perungudi", slug: "perungudi" },
    { name: "Poonamallee", slug: "poonamallee" },
    { name: "Porur", slug: "porur" },
    { name: "Purasawalkam", slug: "purasawalkam" },
    { name: "Ramapuram", slug: "ramapuram" },
    { name: "Royapettah", slug: "royapettah" },
    { name: "Royapuram", slug: "royapuram" },
    { name: "Saidapet", slug: "saidapet" },
    { name: "Selaiyur", slug: "selaiyur" },
    { name: "Semmancheri", slug: "semmancheri" },
    { name: "Sholinganallur", slug: "sholinganallur" },
    { name: "Siruseri", slug: "siruseri" },
    { name: "Tambaram", slug: "tambaram" },
    { name: "T Nagar", slug: "t-nagar" },
    { name: "Teynampet", slug: "teynampet" },
    { name: "Thiruvanmiyur", slug: "thiruvanmiyur" },
    { name: "Thoraipakkam", slug: "thoraipakkam" },
    { name: "Tondiarpet", slug: "tondiarpet" },
    { name: "Triplicane", slug: "triplicane" },
    { name: "Vadapalani", slug: "vadapalani" },
    { name: "Valasaravakkam", slug: "valasaravakkam" },
    { name: "Velachery", slug: "velachery" },
    { name: "Villivakkam", slug: "villivakkam" },
    { name: "Virugambakkam", slug: "virugambakkam" },
    { name: "Washermanpet", slug: "washermanpet" },
    { name: "West Mambalam", slug: "west-mambalam" },
  ],
  services: [
    {
      name: "Balcony Safety Nets",
      slug: "balcony-safety-nets",
      angle: "Apartment balcony fall protection with neat edge finishing.",
    },
    {
      name: "Children Safety Nets",
      slug: "children-safety-nets",
      angle: "Family-focused protection for balconies, windows, and open edges.",
    },
    {
      name: "Anti Bird Nets",
      slug: "anti-bird-nets",
      angle: "Bird entry control for balconies, ducts, shafts, and utility openings.",
    },
    {
      name: "Pigeon Safety Nets",
      slug: "pigeon-safety-nets",
      angle: "Pigeon route blocking for daily-use apartment balconies.",
    },
    {
      name: "Invisible Grills",
      slug: "invisible-grills",
      angle: "Open-view safety cable systems for modern apartment facades.",
    },
    {
      name: "Balcony Invisible Grills",
      slug: "balcony-invisible-grills",
      angle: "Premium balcony protection where the view should stay open.",
    },
    {
      name: "Window Safety Nets",
      slug: "window-safety-nets",
      angle: "Window-level safety and bird protection for family rooms.",
    },
    {
      name: "Duct Area Safety Nets",
      slug: "duct-area-safety-nets",
      angle: "Protection for shafts, ducts, service voids, and utility cuts.",
    },
    {
      name: "Building Covering Safety Nets",
      slug: "building-covering-safety-nets",
      angle: "Large-area facade, shaft, and open-side covering for buildings.",
    },
    {
      name: "Terrace Safety Nets",
      slug: "terrace-safety-nets",
      angle: "Safety coverage for terraces, open upper floors, and play corners.",
    },
    {
      name: "Staircase Safety Nets",
      slug: "staircase-safety-nets",
      angle: "Vertical fall protection for staircases, voids, and duplex edges.",
    },
    {
      name: "Swimming Pool Safety Nets",
      slug: "swimming-pool-safety-nets",
      angle: "Custom safety netting for pools, decks, and common amenities.",
    },
    {
      name: "Cricket Practice Nets",
      slug: "cricket-practice-nets",
      angle: "Containment netting for terraces, academies, and society play zones.",
    },
    {
      name: "Football Sports Nets",
      slug: "football-sports-nets",
      angle: "Sports containment for open play areas and community courts.",
    },
    {
      name: "Bird Spikes Installation",
      slug: "bird-spikes-installation",
      angle: "Bird perch control for ledges, parapets, AC units, and facade edges.",
    },
    {
      name: "Cloth Hanger Installation",
      slug: "cloth-hanger-installation",
      angle: "Balcony and utility drying systems planned around daily use.",
    },
  ],
} as const;
