export const hyderabadLocations = [
  "A G Colony",
  "A S Rao Nagar",
  "Aaditya Nagar",
  "Abdullapurmet",
  "Abids",
  "AC Guards",
  "Adarsh Enclave",
  "Adarsh Nagar",
  "Afzalgunj",
  "Aghapura",
  "Ahmed Nagar",
  "Akbar Road",
  "Alexander Road",
  "Aliabad",
  "Alkapur Township",
  "Almasguda",
  "Alwal",
  "Ambedkar Nagar",
  "Amber Nagar",
  "Amberpet",
  "Ameerpet",
  "Ameerpet X Road",
  "Anand Bagh",
  "Anand Nagar Colony",
  "Ananthagiri",
  "Ankireddypalli",
  "Appa Junction",
  "AS Rao Nagar",
  "Ashok Nagar",
  "Asif Nagar",
  "Athvelly",
  "Attapur",
  "Attapur Ring Road",
  "Auto Nagar",
  "Azamabad",
  "Azampura",
  "Baber Bagh",
  "Bachupally",
  "Badangpet",
  "Badichowdi",
  "Bag Amberpet",
  "Bagh Lingampally",
  "Bahadurpally",
  "Bahadurpura",
  "Bairamalguda",
  "Bakaram",
  "Balamrai",
  "Balanagar",
  "Balapur",
  "Balkampet",
  "Bandimet",
  "Bandlaguda",
  "Bandlaguda Jagir",
  "Banjara Hills",
  "Bansilalpet",
  "Bapuji Nagar",
  "Barkas",
  "Barkatpura",
  "Basheer Bagh",
  "Bazar Ghat",
  "Begum Bazaar",
  "Begumpet",
  "Bhagya Nagar Colony",
  "Bharat Nagar",
  "BHEL",
  "Bhogaram",
  "Bholakpur",
  "Bhongir",
  "Bhuvanagiri",
  "Bibinagar",
  "BK Guda",
  "BN Reddy Nagar",
  "Boduppal",
  "Bogaram",
  "Boggulakunta",
  "Boiguda",
  "Bolarum",
  "Bollaram",
  "Bongloor",
  "Borabanda",
  "Bowenpally",
  "Bowrampet",
  "Boyiguda",
  "Brahim Patnam",
  "Buddha Nagar",
  "Budwel",
  "Burgul",
  "Champapet",
  "Chanda Nagar",
  "Chandanagar",
  "Charminar",
  "Chikkadpally",
  "Chinta Basti",
  "Chintal",
  "Chinthal Basti",
  "Chiran Fort Clubra",
  "Chowmohalla",
  "Dabeerpura",
  "Dabeerpura North",
  "Dadar Colony",
  "Dammaiguda",
  "Darul Shifa",
  "Defence Colony",
  "Devan Devdi",
  "Dhoolpet",
  "Dilsukhnagar",
  "Doddapet",
  "Doodh Bowli",
  "Domalguda",
  "Domara Pocham Pally",
  "Dorabavi",
  "Durga Bhawani Nagar",
  "ECIL",
  "Ecil Post",
  "Ecil X Roads",
  "East Anandbagh",
  "East Marredpally",
  "Erragadda",
  "Erramanzil",
  "Film Nagar",
  "Gachibowli",
  "Gaddiannaram",
  "Ganapathi Nagar",
  "Gandhi Nagar",
  "Ghoshamahal",
  "Golconda",
  "Gopanpally",
  "Gowliguda",
  "Goud Nagar",
  "Gulzar Houz",
  "Gummadidala",
  "Hafeezpet",
  "Hakeempet",
  "Hajipalle",
  "Hanuman Nagar",
  "Hans Nagar",
  "Happy Homes Colony",
  "Haripuri Colony",
  "Hayath Nagar",
  "HCL Colony",
  "HMT Colony",
  "HMT Hills",
  "Himayath Nagar",
  "Hussaini Alam",
  "Hyderguda",
  "IDPL Colony",
  "IDC Colony",
  "Ibrahim Bagh",
  "Ibrahimpatnam",
  "Icrisat Enclave",
  "Indira Nagar",
  "Indira Nagar Colony",
  "Inole",
  "Ismailkhanpet",
  "Jahanuma",
  "Jaihindpuram",
  "Jameen Bazar",
  "Jubilee Hills",
  "JNTU Colony",
  "Kachiguda",
  "Kalkaji Colony",
  "Kamala Nagar",
  "Kamalapuri Colony",
  "Kavadiguda",
  "Kavuri Hills",
  "Keerthanagar",
  "Khairatabad",
  "Kollur",
  "Kondapur",
  "Kothaguda",
  "Kothapet",
  "KPHB Colony",
  "Kukatpally",
  "Kukatpally Housing Board",
  "Lakdikapul",
  "Lingampally",
  "Madhapur",
  "Madhura Nagar",
  "Mahendra Hills",
  "Malkajgiri",
  "Malakpet",
  "Manikonda",
  "Maruthi Nagar",
  "Miyapur",
  "Moghalpura",
  "Moula Ali",
  "Mulugu",
  "Moti Nagar",
  "Nagole",
  "Nallakunta",
  "Nallagandla",
  "Narayanaguda",
  "Nasrullahpura",
  "Naya Nagar",
  "Nehru Nagar",
  "Neredmet",
  "Nizampet",
  "NTR Nagar",
  "Old Alwal",
  "Osman Nagar",
  "Padmarao Nagar",
  "Panjagutta",
  "Parsigutta",
  "Patancheru",
  "Peerzadiguda",
  "Picket",
  "Pillalaramaram",
  "Pochampally",
  "Punjagutta",
  "Puppalaguda",
  "Quthbullapur",
  "Rahmania Nagar",
  "Raghavendra Nagar Colony",
  "Rajendranagar",
  "Ramanthapur",
  "Ramnagar",
  "Red Hills",
  "RTC X Roads",
  "Sainikpuri",
  "Sanathnagar",
  "Santosh Nagar",
  "Secunderabad",
  "Shadnagar",
  "Shamirpet",
  "Shantinagar",
  "Shamshabad",
  "Shivamguda",
  "Siddiq Nagar",
  "Sitaphalmandi",
  "SR Nagar",
  "SRT Colony",
  "Tadbund",
  "Talaab Katta",
  "Talabkatta",
  "Taramatipet",
  "Tarnaka",
  "Tellapur",
  "Toli Chowki",
  "Uppal",
  "Uppal Kalan",
  "Usha Nagar",
  "Vanasthalipuram",
  "Vattepally",
  "Vengal Rao Nagar",
  "Vidyanagar",
  "Warasiguda",
  "West Marredpally",
  "Yadagirigutta",
  "Yakutpura",
  "Yapral",
  "Yellareddy Guda",
  "Yousufguda",
  "Zameerbagh",
  "Zamistanpur",
  "Hitech City",
  "Hi Tech City",
  "Jeedimetla",
  "Financial District",
  "Nanakramguda",
  "Raidurg",
  "Raidurgam",
  "Kokapet",
  "Narsingi",
  "Tellapur Phase 2",
  "Kompally",
  "Medchal",
  "Suchitra",
  "Suchitra Circle",
  "Keesara",
  "Turkapally",
  "Pocharam",
  "Pocharam IT Park",
  "Adibatla",
  "Tukkuguda",
  "Maheshwaram",
  "Shankarpally",
  "Kothur",
  "Chevella",
  "Moinabad",
  "Gandipet",
  "Neknampur",
  "Alkapuri",
  "Kapra",
  "Safilguda",
  "Dr AS Rao Nagar",
  "Chintalakunta",
  "Meerpet",
  "LB Nagar X Roads",
  "Hasthinapuram",
  "Karmanghat",
  "Moosapet",
  "Pragathi Nagar",
  "Mallapur",
  "Nacharam",
  "Upparpally",
  "Santoshnagar Colony",
  "Raj Bhavan Road",
  "Somajiguda",
  "Greenlands",
  "Begumpet Airport Area",
  "Trimulgherry",
  "Mettuguda",
  "Tarnaka X Roads",
  "Secunderabad Cantonment"
];

export const bangaloreLocations = [
"Abbigere",
"Adugodi",
"AECS Layout",
"Akshayanagar",
"Amrutha Halli",
"Anagalapura",
"Anjanapura",
"Annapurneshwari Nagar",
"Andrahalli",
"Anekal",
"Arasanakunte",
"Ashirvad Colony",
"Ashok Nagar",
"Attibele",
"Attiguppe",
"Aavalahalli",
"Azad Nagar",
"B Narayanapura",
"Babusa Palya",
"Bagalakunte",
"Bagaluru",
"Bagepalli",
"Baiyyappanahalli",
"Balagere",
"Ballur",
"Banashankari",
"Banaswadi",
"Bannerghatta",
"Bapuji Nagar",
"Basapura",
"Basavanagar",
"Basavanagudi",
"Basavanna Nagar",
"Basaveshwara Nagar",
"Battarahalli",
"Begur",
"Belathur",
"Bellandur",
"Bennigana Halli",
"Benson Town",
"Bettahalasur",
"Bhaktharahalli",
"Bhoganhalli",
"Bhoopasandra",
"Bhovi Palya",
"Bidrahalli",
"Bidadi",
"Bikkanahalli",
"Bileshivale",
"Binny Pete",
"Bommasandra",
"Bommenahalli",
"Boyalahalli",
"Brigade Road",
"Brookefield",
"Budigere",
"Budihal",
"BTM Layout",
"Byatarayanapura",
"Byrathi",
"Cambridge Layout",
"Carmelaram",
"Chadalapura",
"Chamarajpet",
"Chamundi Nagar",
"Chandapura",
"Chandra Layout",
"Chansandra",
"Chelekare",
"Chikkaballapur",
"Chikka Banaswadi",
"Chikka Tirupathi",
"Chikkagubbi",
"Chikkajala",
"Chikkakannalli",
"Chikkalasandra",
"Chikkanahalli",
"Chikbanavara",
"Chikkathoguru",
"Chinnapa Garden",
"Chinnapanna Halli",
"Chintamani",
"Chokkanahalli",
"Cholanayakanahalli",
"Commercial Street",
"Cooke Town",
"Cottonpete",
"Cox Town",
"CQAL Layout",
"Craig Park Layout",
"CV Raman Nagar",
"Cunningham Road",
"Dabaspete",
"Dasarahalli Hebbal",
"Dasarahalli Main Road",
"Dayananda Nagar",
"Devanahalli",
"Devanahalli Road",
"Devarachikkanahalli",
"Devasthanagalu",
"Devinagar",
"Dodda Aalada Mara Road",
"Dodda Banasvadi",
"Doddabele",
"Doddabommasandra",
"Doddakallasandra",
"Doddakannalli",
"Doddakammanahalli",
"Doddathoguru",
"Dodsworth Layout",
"Domlur",
"Dommasandra",
"Dollars Colony",
"Dooravani Nagar",
"Ejipura",
"Electronic City",
"Essel Gardens",
"Frazer Town",
"Gandhi Nagar",
"Ganapathihalli",
"Ganga Nagar",
"Garden Layout",
"Garudachar Palya",
"Garvebhavi Palya",
"Gattahalli",
"Gauribidanur",
"Girinagar",
"GM Palya",
"Gollahalli",
"Gottigere",
"Gubalala",
"Gunjur",
"Gunjur Mugalur Road",
"Guttahalli",
"HAL Layout",
"Hancharahalli",
"Hanumantha Nagar",
"Haragadde",
"Harlur",
"Harohalli",
"Haudin Road",
"HBR Layout",
"Hebbal",
"Hegde Nagar",
"Hennur",
"Hennur Road",
"Hesaraghatta",
"HMT Layout",
"Hombegowda Nagar",
"Hongasandra",
"Horamavu",
"Horamavu Agara",
"Hosa Road",
"Hosakerehalli",
"Hosapalaya",
"Hoskote",
"Hosur Road",
"HSR Layout",
"Hulimavu",
"Hullahalli",
"Huskur",
"Huttanahalli",
"Immadihalli",
"Indira Nagar",
"Infantry Road",
"International Airport Road",
"ISRO Layout",
"ITPL Road",
"IVC Road",
"Jakkasandra",
"Jakkur",
"Jalahalli",
"Jangamakote",
"Jaya Chamarajendra Nagar",
"Jayamahal",
"Jayanagar",
"JP Nagar",
"Kadabagere",
"Kadubeesanahalli",
"Kadugodi",
"Kadugondanahalli",
"Kaggadasapura",
"Kaggalipura",
"Kaikondrahalli",
"Kalkere",
"Kalasipalayam",
"Kalena Agrahara",
"Kamaksipalya",
"Kamala Nagar",
"Kamanahalli",
"Kammasandra",
"Kanaka Nagar",
"Kanakapura",
"Kannamangala",
"Karthik Nagar",
"Kasturi Nagar",
"Kathriguppe",
"Kattigenahalli",
"Kaval Byrasandra",
"Kempegowda Nagar",
"Kempapura",
"Kengeri",
"Kithiganur",
"Kodathi",
"Kodichikkanahalli",
"Kodigehalli",
"Kodihalli",
"Kodipur",
"Kogilu",
"Kolar Road",
"Kolar-Chikkaballapur Road",
"Kommaghatta",
"Konanakunte",
"Koramangala",
"Koralur",
"Kothanur",
"Kothanoor",
"Koti Hosahalli",
"K R Puram",
"Krishnarajapuram",
"Kudlu",
"Kudlu Gate",
"Kumbalgodu",
"Kundalahalli",
"Kunigal Road",
"Kuthaganahalli",
"LB Shastri Nagar",
"Laggere",
"Lakshmamma Layout",
"Lake City",
"Langford Road",
"Langford Town",
"Lavelle Road",
"Lingarajapuram",
"Lingadheeranahalli",
"Madiwala",
"Madhava Nagar",
"Magadi Road",
"Mahadevapura",
"Mahalakshmi Layout",
"Majestic",
"Mallathahalli",
"Malleshpalya",
"Malleshwaram",
"Malur-Hosur Road",
"Marathahalli",
"Maruthi Nagar",
"Mathikere",
"Medihalli",
"Mico Layout",
"Millers Road",
"MG Road",
"Munireddy Layout",
"Munnekollal",
"Murugeshpalya",
"Mysore Road",
"Nagasandra",
"Nagadevanahalli",
"Nagarbhavi",
"Nagavara",
"Nagondanahalli",
"Nallurhalli",
"Nandi Hills",
"Nanjappa Garden",
"Narasapura",
"Nayanda Halli",
"Neelasandra",
"Neeladri Nagar",
"Nehru Nagar",
"Nelamangala",
"New BEL Road",
"New Thippasandra",
"Nobo Nagar",
"NRI Layout",
"Off Sarjapur road",
"Old Airport Road",
"Old Madras Road",
"OMBR Layout",
"Outer Ring Road",
"Padmanabha Nagar",
"Pai Layout",
"Palace Road",
"Panathur",
"Panduranga Nagar",
"Pattandur Agrahara",
"Peenya",
"Prashanth Nagar",
"Rachenahalli",
"Race Course Road",
"Raghavendra Colony",
"Ragavendra Nagar",
"Rajaji Nagar",
"Rajanukunte",
"Rajiv Gandhi Nagar",
"Raja Rajeshwari Nagar",
"Ramagondanahalli",
"Ramamurthy Nagar",
"Ramohalli",
"Rayasandra",
"Residency Road",
"Rest House Road",
"Richards Town",
"Richard's Park",
"Richmond Road",
"Richmond Town",
"Roopena Agrahara",
"RT Nagar",
"S.Medihalli",
"Sadashiva Nagar",
"Sadduguntepalya",
"Sahakara Nagar",
"Sampangi Rama Nagar",
"Sampigehalli",
"Sanjay Nagar",
"Sankey Road",
"Sarjapur",
"Sarjapur Road",
"Seegehalli",
"Seenappa Layout",
"Seshadripuram",
"Shankarapura",
"Shanthi Nagar",
"Shanthi Pura",
"Shanthala Nagar",
"Shettihalli",
"Shigehalli",
"Shivaji Nagar",
"Siddapura",
"Silk Board",
"Silver Springs Layout",
"Singanahalli",
"Singasandra",
"SMV Layout",
"Solur",
"Somashetti Halli",
"Sompura",
"Sonnenahalli",
"Soundarya Layout",
"Soukya Road",
"Srinagar",
"Srinivasa Nagar",
"Srirampura",
"St. Johns Road",
"Subramanyapura",
"Sudhama Nagar",
"Sunkadakatte",
"Suryanagar",
"T Dasarahalli",
"Talaghattapura",
"Tavarekere-BTM",
"TC Palya Road",
"Teacher's Colony",
"Tharabanahalli",
"Tharaballi",
"Thanisandra",
"Thippasandra",
"Thubarahalli",
"Tippenahalli",
"Tilak Nagar",
"Tumkur Road",
"Ulsoor",
"Ullal",
"Uttarahalli",
"Vaderahalli",
"Varthur",
"Vasanth Nagar",
"Vasanthapura",
"Venkatagiri Kote",
"Venkatapura",
"Venkateshpuram",
"Victoria Layout",
"Vidyaranyapura",
"Vignana Nagar",
"Vijaya Bank Colony",
"Vijayanagar",
"Vijaypura",
"Vinayaka Layout",
"Virupakshapura",
"Vishweshwaraiah Layout",
"Vittal Nagar",
"Viveka Nagar",
"Wheeler Road",
"Whitefield",
"Williams Town",
"Wind Tunnel Road",
"Yelahanka",
"Yelanahalli",
"Yemalur",
"kalyan nagar"
]

export const aprtmentsLocationsfromBengalore = [
"Prestige Shantiniketan, Whitefield",
"The Prestige City, Sarjapur Road",
"Prestige Lakeside Habitat, Varthur",
"Prestige Jindal City, Tumkur Road",
"Brigade Utopia, Whitefield",
"Embassy Springs, Devanahalli",
"Sobha City, Thanisandra",
"Nambiar District 25, Sarjapur Road",

"Brigade Cosmopolis, Whitefield",
"Divyasree Republic of Whitefield, ITPL",
"Sobha Dream Acres, Panathur",
"Prestige Waterford, Whitefield",
"Prestige Fontaine Bleau, Whitefield",
"Purva Palm Beach, Hennur",
"Total Environment Windmills of Your Mind, Whitefield",
"Brigade Lakefront, Whitefield",
"Assetz Marq, Whitefield",

"Prestige Ferns Residency, Bellandur",
"Sobha Royal Pavilion, Sarjapur Road",
"Purva Skywood, Sarjapur Road",
"Assetz East Point, Sarjapur Road",
"Adarsh Palm Retreat, Bellandur",
"Mana Capitol, Sarjapur Road",
"Godrej 24, Sarjapur Road",
"Salarpuria Sattva Greenage, HSR Layout",

"Prestige Sunrise Park, Electronic City",
"Ajmera Infinity, Electronic City",
"SNN Raj GreenBay, Electronic City Phase 2",
"Shriram Signiaa, Electronic City",
"GM Infinite E-City Town, Electronic City",

"Karle Zenith Residences, Hebbal",
"Godrej Woodsman Estate, Hebbal",
"Century Breeze, Jakkur",
"Brigade Northridge, Kogilu",
"Purva Atmosphere, Thanisandra",
"NR Orchid Gardenia, Yelahanka",
"Provident Welworth City, Yelahanka",

"Prestige Falcon City, Kanakapura Road",
"Mantri Serenity, Kanakapura Road",
"Brigade Meadows, Kanakapura Road",
"Sobha Forest View, Kanakapura Road",
"Purva Highland, Kanakapura Road",

"Prestige Kingfisher Towers, UB City",
"UB City Residences, Central Bangalore",
"Embassy One, Hebbal",

"Prestige Park Grove, Whitefield",
"Prestige Lavender Fields, Sarjapur Road",
"Prestige Elm Park, Whitefield",
"Prestige Song of the South, Begur Road",
"Prestige Notting Hill, Bannerghatta Road",

"Brigade Cornerstone Utopia Eden, Whitefield",
"Brigade Exotica, Old Madras Road",
"Brigade Golden Triangle, Old Madras Road",
"Brigade Millennium, JP Nagar",
"Brigade Paramount, Sarjapur Road",

"Sobha Arena, Kanakapura Road",
"Sobha Dream Gardens, Thanisandra",
"Sobha Indraprastha, Rajajinagar",
"Sobha HRC Pristine, Jakkur",
"Sobha Habitech, Whitefield",

"Puravankara Purva Westend, Magadi Road",
"Purva Venezia, Yelahanka",
"Purva Fountain Square, Marathahalli",
"Purva Riviera, Marathahalli",
"Purva Sunflower, Bellandur",

"Godrej Air, Whitefield",
"Godrej Eternity, Kanakapura Road",
"Godrej Reflections, Sarjapur Road",
"Godrej Aqua, International Airport Road",
"Godrej Royale Woods, Devanahalli",

"Assetz 63 Degree East, Sarjapur Road",
"Assetz Sun & Sanctum, KR Puram",
"Assetz Earth & Essence, Hosur Road",

"Total Environment Pursuit of a Radical Rhapsody, Whitefield",
"Total Environment After The Rain, Yelahanka",

"Embassy Lake Terraces, Hebbal",
"Embassy Pristine, Bellandur",
"Embassy Grove, Indiranagar",

"Adarsh Palm Meadows, Whitefield",
"Adarsh Tranqville, Hennur",
"Adarsh Tropica, Sarjapur Road",

"Salarpuria Sattva Luxuria, Malleshwaram",
"Salarpuria Sattva Divinity, Mysore Road",
"Salarpuria Sattva Aspire, Hennur",

"Prestige Silver Oak, Whitefield",
"Prestige White Meadows, Whitefield",
"Prestige Dolce Vita, Whitefield",

"L&T Raintree Boulevard, Hebbal",
"L&T South City, Bannerghatta Road",

"Raheja Residency, Koramangala",
"Raheja Pebble Bay, Hebbal",

"HM World City, JP Nagar",
"Mahaveer Ranches, Kengeri",
"DS Max Skycity, Thanisandra",

"Shapoorji Pallonji Parkwest, Binnypet",
"Shapoorji Pallonji Vanaha, Yelahanka",

"Kolte Patil Mirabilis, Horamavu",
"Kolte Patil iTowers Exente, Whitefield",

"Century Ethos, Hebbal",
"Century Breeze Phase 2, Jakkur",

"Concorde Napa Valley, Kanakapura Road",
"Concorde Spring Meadows, Kanakapura Road",

"Vaishnavi Serene, Yelahanka",
"Vaishnavi Oasis, JP Nagar",

"Rohan Iksha, Bhoganhalli",
"Rohan Vasantha, Whitefield",
"Rohan Upavan, Hennur"
];

export const combineBengaloreLocations = [
...bangaloreLocations,
...aprtmentsLocationsfromBengalore
]